version: "3"

volumes:
  wikijs_config_letsencrypt:
    external: true

#db-data:

networks:
  telegramnet:
    driver: bridge
      #dbnet:
      #driver: bridge


services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-tgbots
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./telegram_ssl:/etc/telegram_ssl:ro
      - wikijs_config_letsencrypt:/etc/letsencrypt:ro
    ports:
      - "5000:5000"
      - "8443:8443"
      - "88:88"
    networks:
      - telegramnet
    depends_on:
      - oitestbot
      - oitheatrebot
      - oimailbot

  oitestbot:
    build:
      context: .
    environment:
      BOT_NAME: oitestbot
      FLASK_ENV: production
    image: oitheatre/pytgflask
    container_name: oitestbot
    networks:
      - telegramnet

  oitheatrebot:
    build:
      context: .
    environment:
      BOT_NAME: oitheatrebot
      FLASK_ENV: production
    image: oitheatre/pytgflask
    container_name: oitheatrebot
    networks:
      - telegramnet

  oimailbot:
    build:
      context: .
    environment:
      BOT_NAME: oimailbot
      FLASK_ENV: production
    image: oitheatre/pytgflask
    container_name: oimailbot
    networks:
      - telegramnet

        #  db:
        #    image: postgres:9-alpine
        #    container_name: postgres_db
        #    environment:
        #      POSTGRES_DB: wiki
        #      POSTGRES_USER: wikijs
        #      POSTGRES_PASSWORD: wikijsrocks
        #    volumes:
        #      - db-data:/var/lib/postgresql/data
        #    networks:
        #      - dbnet
