version: "3"

volumes:
  db-data:

networks:
  dbnet:
    driver: bridge
  telegramnet:
    driver: bridge


services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro
    ports:
      - "88:88"
      - "8443:8443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - telegramnet
    #depends_on:

  db:
    image: postgres:9-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dbnet

  oitestbot:
    build:
      context: .
    image: oitheatre/pytgflask
    container_name: oitestbot
    command: [ "oitestbot" ]
    networks:
      - telegramnet
